Description: Create the IAM and Lambda resource for S3 to Flywheel import operations
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  S3FlywheelImportRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3FlywheelImportRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3FlywheelImportRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: arn:aws:ssm:*:*:parameter/prod/flywheel/gearbot/apikey
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:log-group:/aws/lambda/S3FlywheelImport:*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::loni-table-data
                  - arn:aws:s3:::loni-table-data/*
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'

  S3FlywheelImport:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: S3FlywheelImport
      Policies:
      - AWSXrayWriteOnlyAccess
      Tracing: Active
      Role: !GetAtt S3FlywheelImportRole.Arn
      VpcConfig:
        SecurityGroupIds:
        - sg-0503342ee72448012
        SubnetIds:
        - subnet-0438422c144d3a271
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          STORAGE_ID: "691c926ff8220b709983b848"
          GROUP: "loni"
          API_KEY_PATH: "/prod/flywheel/gearbot/apikey"
          STUDIES: '[{"project_label":"ingest-metadata-scan","filter_pattern":"clariti","filter_mode":"exclude"},{"project_label":"ingest-metadata-clariti","filter_pattern":"clariti","filter_mode":"include"}]'
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: Dockerfile
